# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'resultGUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ResultWindow(object):
    def setupUi(self, ResultWindow):
        ResultWindow.setObjectName("ResultWindow")
        ResultWindow.resize(779, 379)
        font = QtGui.QFont()
        font.setPointSize(8)
        ResultWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../search_duplicate.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ResultWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(ResultWindow)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.centralwidget.setFont(font)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.title_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.title_label.setFont(font)
        self.title_label.setObjectName("title_label")
        self.horizontalLayout_2.addWidget(self.title_label)
        self.del_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.del_pushButton.setEnabled(False)
        self.del_pushButton.setAutoRepeatDelay(300)
        self.del_pushButton.setObjectName("del_pushButton")
        self.horizontalLayout_2.addWidget(self.del_pushButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.all_radioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.all_radioButton.setChecked(True)
        self.all_radioButton.setObjectName("all_radioButton")
        self.buttonGroup = QtWidgets.QButtonGroup(ResultWindow)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.all_radioButton)
        self.horizontalLayout_3.addWidget(self.all_radioButton)
        self.picture_radioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.picture_radioButton.setObjectName("picture_radioButton")
        self.buttonGroup.addButton(self.picture_radioButton)
        self.horizontalLayout_3.addWidget(self.picture_radioButton)
        self.video_radioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.video_radioButton.setObjectName("video_radioButton")
        self.buttonGroup.addButton(self.video_radioButton)
        self.horizontalLayout_3.addWidget(self.video_radioButton)
        self.doc_radioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.doc_radioButton.setObjectName("doc_radioButton")
        self.buttonGroup.addButton(self.doc_radioButton)
        self.horizontalLayout_3.addWidget(self.doc_radioButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.original_listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.original_listWidget.setObjectName("original_listWidget")
        self.horizontalLayout.addWidget(self.original_listWidget)
        self.dup_listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.dup_listWidget.setObjectName("dup_listWidget")
        self.horizontalLayout.addWidget(self.dup_listWidget)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        ResultWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(ResultWindow)
        QtCore.QMetaObject.connectSlotsByName(ResultWindow)

    def retranslateUi(self, ResultWindow):
        _translate = QtCore.QCoreApplication.translate
        ResultWindow.setWindowTitle(_translate("ResultWindow", "Search result"))
        self.title_label.setText(_translate("ResultWindow", "TextLabel"))
        self.del_pushButton.setText(_translate("ResultWindow", "Delete File"))
        self.all_radioButton.setText(_translate("ResultWindow", "All Files"))
        self.picture_radioButton.setText(_translate("ResultWindow", "Pictures"))
        self.video_radioButton.setText(_translate("ResultWindow", "Videos"))
        self.doc_radioButton.setText(_translate("ResultWindow", "Documents"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ResultWindow = QtWidgets.QMainWindow()
    ui = Ui_ResultWindow()
    ui.setupUi(ResultWindow)
    ResultWindow.show()
    sys.exit(app.exec_())
